### ISSUE TITLE
Question about `clean` results of K400 & SSv2

### ISSUE THREAD

**Issue by BinhuiXie** [wlin-at/ViTTA#5]
Hi @wlin-at 

Excellent works! 

Here are some questions about the results in Table 1. In your paper, the `clean` refers to the performance of the model on the original validation set. Specifically, for K400 & SSv2, the results are 75.32 and 66.36, respectively. But the results of [VideoSwin](https://github.com/SwinTransformer/Video-Swin-Transformer) repo give higher results. 

<img width="754" alt="image" src="https://github.com/wlin-at/ViTTA/assets/28836514/9f52926b-3695-434e-859e-66acf8450d0e">

<img width="754" alt="image" src="https://github.com/wlin-at/ViTTA/assets/28836514/87872010-f105-45e9-bac1-42aa027a5ece">

Could you help me out? I really appreciate any help you can provide.

**Comment by wlin-at** [comment]
> Hi @wlin-at
> 
> Excellent works!
> 
> Here are some questions about the results in Table 1. In your paper, the `clean` refers to the performance of the model on the original validation set. Specifically, for K400 & SSv2, the results are 75.32 and 66.36, respectively. But the results of [VideoSwin](https://github.com/SwinTransformer/Video-Swin-Transformer) repo give higher results.
> <img alt="image" width="754" src="https://user-images.githubusercontent.com/28836514/255791546-9f52926b-3695-434e-859e-66acf8450d0e.png"> <img alt="image" width="754" src="https://user-images.githubusercontent.com/28836514/255791613-87872010-f105-45e9-bac1-42aa027a5ece.png">
> 
> Could you help me out? I really appreciate any help you can provide.

Hi thanks for the interest in the work! 
[VideoSwin](https://arxiv.org/pdf/2106.13230.pdf) uses 4x3 = 12 views during inference and the final score is computed as the average score over all the views. In our inference, we only take 1x1 view (center crop, uniformly sample one clip) for inference on clean, and for test time adaptation for efficient implementation. The implementation details are given in both papers.

**Comment by BinhuiXie** [comment]
thanks a lot
